### ISSUE TITLE
win1021H1 打不开这个软件，无法弹出界面

### ISSUE THREAD

**Issue by alrt9** [danalite/autool#6]
![image](https://github.com/danalite/autool/assets/48048711/f7563513-9a14-40bc-bedd-cf48227b1e9a)
![image](https://github.com/danalite/autool/assets/48048711/15009229-80c5-409b-8ead-84e8b8cd0c4b)

**Comment by vrteee** [comment]
@alrt9 你在系统托盘(dock) 里面有看到AuTool的图标吗？如果有的话，你可以试一下 双击 Windows 键，然后看看窗口能显示出来吗

**Comment by alrt9** [comment]
> @alrt9你在系统托盘（dock）里面有看到AuTool的图标吗？如果有的话，你可以试一下左边的Windows按键，然后看看窗口能显示出来吗？

看不到

**Comment by vrteee** [comment]
初始化的问题 会尽快修复

```shell
[ NodeJS ] appHome:  /Users/hc/Desktop/apps-temp
(node:28455) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/Users/hc/Desktop/apps-temp/background.log'
    at statSync (node:fs:1596:3)
    at t.statSync (node:electron/js2c/asar_bundle:2:4510)
    at te (/Users/hc/Desktop/autoo/release/mac/AuTool.app/Contents/Resources/app.asar/background.js:8:179621)
    at re (/Users/hc/Desktop/autoo/release/mac/AuTool.app/Contents/Resources/app.asar/background.js:8:180594)
    at /Users/hc/Desktop/autoo/release/mac/AuTool.app/Contents/Resources/app.asar/background.js:8:185616
```

**Comment by vrteee** [comment]
@alrt9 试试0.1.12 我这边可以用了
